### ISSUE TITLE
package.json?

### ISSUE THREAD

**Issue by admonkey** [jessgusclark/gadget-checkin#11]
I'm still new to npm, but why do you have package.json in the .gitignore? I had to manually add each missing gulp dependency as I slugged through the build errors.

**Comment by jessgusclark** [comment]
This is one of those unique times when I use `git blame` and see that it is not my fault! This repo was built off the gadget starter and it looks like Brandon ignored it; not sure why but I missed un-ignoring it.

Thanks!

**Comment by jessgusclark** [comment]
Resolved with Pull Request #13
