### ISSUE TITLE
bug: show/hide sites toggle on refresh

### ISSUE THREAD

**Issue by admonkey** [jessgusclark/gadget-checkin#9]
refresh button invalidates show/hide sites without checked out files. when you click refresh, the list state always goes to collapsed, and toggle button persists in whichever state it was in last.

**Comment by jessgusclark** [comment]
Thanks for letting me know! I"m out sick today but I'll look into this in the next few days.

Thanks!

**Comment by jessgusclark** [comment]
Resolved with Pull Request #13
